FROM streamsheets-core

LABEL org.opencontainers.image.source="https://github.com/ctron/streamsheets-kubernetes"

WORKDIR /streamsheets

ENV NODE_ENV="production"

CMD node /streamsheets/packages/service-graphs/start.js
